# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ab6b4a6d16ef8b916df5a0b515de2e3499198b813d00eae6043da8641fbfd48171cc2a309a212167d9aab995a4cd409fec86f34087d97ce27794611d20773a2

test:
  secret_key_base: c3e2f8861248b2f040b0fd1a3d503e7f7a557417419ba8662799e697c25e8d28cc20d0e50ce37ed08c1c549dc557a5ceac93c765798305457841170a340ffab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
